In [1]:
from langchain_community.embeddings import OllamaEmbeddings
from langchain.document_loaders import TextLoader, UnstructuredMarkdownLoader, CSVLoader  # Use TextLoader for markdown
import chromadb
# No OpenAIEmbeddings needed (using Ollama)
from langchain.text_splitter import MarkdownTextSplitter, CharacterTextSplitter, MarkdownHeaderTextSplitter  # Use MarkdownTextSplitter
from langchain.vectorstores import Chroma
from langchain_community.llms import Ollama
from langchain_community.embeddings.sentence_transformer import (
    SentenceTransformerEmbeddings,
)

c:\Users\user5\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(

In [2]:


# Ollama configuration (assuming locally running Ollama with Phi model)
embeddings = OllamaEmbeddings(model="nomic-embed-text")
llm = Ollama(model="phi")
# create the open-source embedding function
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

# Load markdown file (replace with your path)
# loader = TextLoader("./table_info/table_data.md")
# data = loader.load()
loader = TextLoader("./try.md")
data = loader.load()


# Split markdown text into documents

In [3]:
data[0].page_content

"1. biometrics_body_temperature\n\n``` sql\nCREATE TABLE `biometrics_body_temperature` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_body_temperature\n  `EhrId` varchar(128) DEFAULT NULL,\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --patient id of patient test performed on\n  `TerraSummaryId` varchar(128) DEFAULT NULL,\n  `Provider` varchar(128) DEFAULT NULL, ---provider who performed test on patient\n  `BodyTemperature` float NOT NULL, --- temperature of patient \n  `Unit` varchar(8) NOT NULL DEFAULT 'Â°F', ---unit of temperature\n  `RecordDate` datetime DEFAULT NULL, ---body temperature record date\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of user who recorded the temperature\n  `CreatedAt` datetime DEFAULT NULL, --- created at timestamp\n  `UpdatedAt` datetime NOT NULL,  --- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,    -- deleted if set to not null\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n\n```\n##\n\n\n2. biometrics_body_height\n``` sql\nCREATE TABLE `biometrics_body_height` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_body_height\n  `EhrId` varchar(128) DEFAULT NULL, --- Electronics  Health Record ID\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of person\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --- id of patient\n  `BodyHeight` float NOT NULL, --- height of patient\n  `Unit` varchar(8) NOT NULL DEFAULT 'cm', ---measured unit of height \n  `RecordDate` datetime DEFAULT NULL, ---recorded date of patient height\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of user who recorded the height\n  `CreatedAt` datetime DEFAULT NULL, ---created time stamp\n  `UpdatedAt` datetime NOT NULL,    ---updated time stamp\n  `DeletedAt` datetime DEFAULT NULL,    --set to not null when data is deleted\n  PRIMARY KEY (`id`),\n  KEY `PersonId` (`PersonId`),\n  KEY `PatientUserId` (`PatientUserId`),\n  CONSTRAINT `biometrics_body_height_ibfk_21` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `biometrics_body_height_ibfk_22` FOREIGN KEY (`PatientUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n##\n\n\n\n3. biometrics_blood_pressure \n``` sql\nCREATE TABLE `biometrics_blood_pressure` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_blood_pressure\n  `EhrId` varchar(128) DEFAULT NULL, --- electronics  health records id\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, -- id of person\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, -- id of patient\n  `TerraSummaryId` varchar(128) DEFAULT NULL,  -- terra summary id for this data\n  `Provider` varchar(128) DEFAULT NULL,          -- provider who recorded the data\n  `Systolic` float NOT NULL, --maximum blood presure recorded\n  `Diastolic` float NOT NULL, --minimum blood pressure recorded\n  `Unit` varchar(8) NOT NULL DEFAULT 'mm-Hg',     --unit of measurement\n  `RecordDate` datetime DEFAULT NULL,              --date when the reading was taken\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,    --user who took the record\n  `CreatedAt` datetime DEFAULT NULL,                -- created timestamp\n  `UpdatedAt` datetime NOT NULL,                    -- updated timestamp\n  `DeletedAt` datetime DEFAULT NULL,                 -- deleted timestamp\n  PRIMARY KEY (`id`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `biometrics_blood_pressure_ibfk_1` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n\n4. biometrics_blood_oxygen_saturation\n``` sql\n  CREATE TABLE `biometrics_blood_oxygen_saturation` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_blood_oxygen_saturation\n  `EhrId` varchar(128) DEFAULT NULL,  ---Electronics  Health Record ID\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of patient\n  `TerraSummaryId` varchar(128) DEFAULT NULL, --- ID from Terra's system\n  `Provider` varchar(128) DEFAULT NULL,  --- provider name\n  `BloodOxygenSaturation` float NOT NULL, ---oxygen level in blood\n  `Unit` varchar(8) NOT NULL DEFAULT '%',     ---unit of oxygen saturation\n  `RecordDate` datetime DEFAULT NULL,         ---date when the measurement was taken\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who took the measurement\n  `CreatedAt` datetime DEFAULT NULL,            ---created time stamp\n  `UpdatedAt` datetime NOT NULL,                 ---updated time stamp\n  `DeletedAt` datetime DEFAULT NULL, -- deleted timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n\n\n\n##\n\n\n5. biometrics_blood_glucose\n``` sql\n CREATE TABLE `biometrics_blood_glucose` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_blood_glucose\n  `EhrId` varchar(128) DEFAULT NULL, ---Electronics  Health Record Id\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of person\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of patient\n  `TerraSummaryId` varchar(128) DEFAULT NULL,  ---summary id for data source\n  `Provider` varchar(128) DEFAULT NULL, ---provider  name who provide this glucose record\n  `BloodGlucose` float NOT NULL,  ---glucose quantity in users blood\n  `A1CLevel` float DEFAULT NULL,      --percentage of total hemoglobin\n  `Unit` varchar(8) NOT NULL DEFAULT 'mg/dL', ---unit of  measurement\n  `RecordDate` datetime DEFAULT NULL,     ---date when the glucose was taken\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who recorded it\n  `CreatedAt` datetime DEFAULT NULL,        ---creation time stamp\n  `UpdatedAt` datetime NOT NULL,             ---update time stamp\n  `DeletedAt` datetime DEFAULT NULL,            ---deletion timestamp\n  PRIMARY KEY (`id`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `biometrics_blood_glucose_ibfk_1` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n\n##\n\n6. biometrics_blood_cholesterol\n``` sql\nCREATE TABLE `biometrics_blood_cholesterol` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_blood_cholesterol\n  `EhrId` varchar(128) DEFAULT NULL, ---electronic  health record id\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---id of person\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of user\n  `TotalCholesterol` float DEFAULT NULL,  ---patient cholesterol \n  `HDL` float DEFAULT NULL,              --good cholestrol\n  `LDL` float DEFAULT NULL,                --bad cholestrol\n  `TriglycerideLevel` float DEFAULT NULL, ---triglycerides in the blood\n  `Ratio` float DEFAULT NULL,              ---ratio between good and bad chol\n  `A1CLevel` float DEFAULT NULL,            ---a1c level in the blood\n  `Unit` varchar(8) DEFAULT 'mg/dl',        ---unit for all values\n  `RecordDate` datetime DEFAULT NULL,        ---date when test was done\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,    --user who took the test\n  `CreatedAt` datetime DEFAULT NULL,          --created timestamp\n  `UpdatedAt` datetime NOT NULL,                 --updated timestamp\n  `DeletedAt` datetime DEFAULT NULL,             --deleted timestamp\n  PRIMARY KEY (`id`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `biometrics_blood_cholesterol_ibfk_1` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n7. biometrics_body_weight\n``` sql\nCREATE TABLE `biometrics_body_weight` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each biometrics_body_weight\n  `EhrId` varchar(128) DEFAULT NULL,  ---electronic health record id\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---patient user id \n  `BodyWeight` float NOT NULL, --- body weight of patient\n  `Unit` varchar(8) NOT NULL DEFAULT 'Kg', ---unit   of measurement for body weight\n  `RecordDate` datetime DEFAULT NULL,  --date when the data was recorded\n  `RecordedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,  ---user who recorded this data\n  `CreatedAt` datetime DEFAULT NULL,     --timestamp when created\n  `UpdatedAt` datetime NOT NULL,           --timestamp when updated\n  `DeletedAt` datetime DEFAULT NULL,        --timestamp when deleted\n  PRIMARY KEY (`id`),\n  KEY `PatientUserId` (`PatientUserId`),\n  CONSTRAINT `biometrics_body_weight_ibfk_1` FOREIGN KEY (`PatientUserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n\n##\n\n\n\n\n8. blood_donation_volunteers\n``` sql\n  CREATE TABLE `blood_donation_volunteers` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each blood_donation_volunteers\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --id of user\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, -- id of person\n  `DisplayId` varchar(24) NOT NULL,  -- display name for volunteer\n  `EhrId` varchar(256) DEFAULT NULL,  -- ehr id from other system\n  `BloodGroup` varchar(16) DEFAULT NULL, -- blood group of patient\n  `LastDonationDate` datetime DEFAULT NULL,  -- last donation date\n  `MedIssues` varchar(1024) DEFAULT NULL,  -- medical issues that the volunteer has\n  `IsAvailable` tinyint(1) NOT NULL DEFAULT '0',  -- is available to donate or not\n  `SelectedBloodGroup` varchar(16) DEFAULT NULL,   -- selected blood group by volunteer\n  `SelectedBridgeId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,    -- bridge id which will be used if there\n  `SelectedPhoneNumber` varchar(16) DEFAULT NULL,     -- phone number of volunteer\n  `LastDonationRecordId` varchar(64) DEFAULT NULL,      -- record id of last donation\n  `CreatedAt` datetime DEFAULT NULL,                     -- timestamp when created\n  `UpdatedAt` datetime NOT NULL,                           -- timestamp when updated\n  `DeletedAt` datetime DEFAULT NULL,                         -- timestamp when deleted\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `blood_donation_volunteers_ibfk_21` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `blood_donation_volunteers_ibfk_22` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n9. blood_donors\n``` sql\nCREATE TABLE `blood_donors` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each blood_donors\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---user id user \n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --- id of person\n  `DisplayId` varchar(24) NOT NULL,                                --- display id\n  `EhrId` varchar(256) DEFAULT NULL,                                --- ehr id\n  `BloodGroup` varchar(16) DEFAULT NULL, --blood group of donors  \n  `AcceptorUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---acceptor user id if any\n  `LastDonationDate` datetime DEFAULT NULL,                           --- last donation date and time\n  `DonorType` varchar(32) NOT NULL DEFAULT 'Blood bridge',            --- Donor type can be Blood Bridge or\n  `MedIssues` varchar(1024) DEFAULT NULL,                              --- Medical issues if any\n  `IsAvailable` tinyint(1) NOT NULL DEFAULT '0',                           --- Is available to donate now?\n  `HasDonatedEarlier` tinyint(1) NOT NULL DEFAULT '0',                      --- Has the user ever donated before\n  `CreatedAt` datetime DEFAULT NULL,                                         --- created at timestamp\n  `UpdatedAt` datetime NOT NULL,                                                 --- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                                                 --- delete at timestamp\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `blood_donors_ibfk_21` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `blood_donors_ibfk_22` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n10. custom_tasks\n``` sql\nCREATE TABLE `custom_tasks` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each custom_tasks\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --id of user\n  `Task` varchar(128) DEFAULT NULL,  -- task\n  `Description` varchar(256) DEFAULT NULL, --task description\n  `Category` varchar(128) DEFAULT 'Custom', --category of the task\n  `ActionType` varchar(64) NOT NULL DEFAULT 'Custom', --type of action like Custom, Reminder etc\n  `Details` text NOT NULL,  --details about the task\n  `ScheduledStartTime` datetime DEFAULT NULL, --task start time\n  `ScheduledEndTime` datetime DEFAULT NULL,-- task end time\n  `Started` tinyint(1) NOT NULL DEFAULT '0', --is started or not\n  `StartedAt` datetime DEFAULT NULL,   --started at timestamp\n  `Finished` tinyint(1) NOT NULL DEFAULT '0', -- is finished or not\n  `FinishedAt` datetime DEFAULT NULL,     --finished at timestamp\n  `Cancelled` tinyint(1) NOT NULL DEFAULT '0',  -- cancelled by user or system\n  `CancelledAt` datetime DEFAULT NULL,        --cancelled at timestamp\n  `CancellationReason` varchar(128) DEFAULT NULL,     --reason for cancelling the task\n  `IsRecurrent` tinyint(1) NOT NULL DEFAULT '0',         --if it's recurring task\n  `RecurrenceScheduleId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,     --recurrence schedule id if any\n  `CreatedAt` datetime DEFAULT NULL,                 --created at timestamp\n  `UpdatedAt` datetime NOT NULL,                           --updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                                --delete at timestamp\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  CONSTRAINT `custom_tasks_ibfk_1` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n11. doctors\n``` sql\nCREATE TABLE `doctors` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each doctors\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --- id of user\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,-- id of person\n  `DisplayId` varchar(24) NOT NULL,                             ----display name to show in UI\n  `NationalDigiDoctorId` varchar(32) DEFAULT NULL, --doctors national id\n  `EhrId` varchar(256) DEFAULT NULL,                ------ehr system unique id\n  `About` varchar(1024) DEFAULT NULL,                --about doctor\n  `Locality` varchar(32) DEFAULT NULL,                --locality where the doctor is located\n  `Qualifications` varchar(256) DEFAULT NULL,           --qualification and specialization\n  `PractisingSince` datetime DEFAULT NULL,             --year when started practicing\n  `Specialities` varchar(1024) DEFAULT NULL,--specialities of doctor\n  `ProfessionalHighlights` varchar(2048) DEFAULT NULL, --professional highlights/achievements\n  `ConsultationFee` float DEFAULT NULL,                --consultation fee per minute or hour\n  `CreatedAt` datetime DEFAULT NULL,                     --created at timestamp\n  `UpdatedAt` datetime NOT NULL,                             --updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                                --delete at timestamp\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `doctors_ibfk_21` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `doctors_ibfk_22` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n\n##\n\n\n12. health_priorities\n``` sql\nCREATE TABLE `health_priorities` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each health_priorities\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --- id of patient\n  `Source` varchar(32) NOT NULL, ---source of the priority \n  `Provider` varchar(64) NOT NULL, ---provider who set this priority\n  `ProviderEnrollmentId` varchar(32) NOT NULL, ---enrollment number in provider system\n  `ProviderCareplanCode` varchar(64) NOT NULL,  ---code that identifies care plan in provider system\n  `ProviderCareplanName` varchar(64) NOT NULL, ---name of care plan in provider system\n  `HealthPriorityType` varchar(64) DEFAULT NULL, ---type of health priority: chronic disease,\n  `StartedAt` datetime DEFAULT NULL,  ---when user started to have this health priority\n  `CompletedAt` datetime DEFAULT NULL, --- when user completed treatment for this health priority\n  `Status` varchar(128) DEFAULT NULL, ---status of health priority: active,completed\n  `ScheduledEndDate` datetime DEFAULT NULL, ---date when treatment should be finished\n  `IsPrimary` tinyint(1) DEFAULT NULL, ---is primary health priority or not\n  `CreatedAt` datetime DEFAULT NULL,          ----created at timestamp\n  `UpdatedAt` datetime NOT NULL,                -----updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                 -------delete at timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```\n\n##\n\n\n\n \n13. health_priority_types\n``` sql\nCREATE TABLE `health_priority_types` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each health_priority_types\n  `Type` varchar(256) NOT NULL, --- Type of Health Priority Type\n  `Tags` varchar(512) DEFAULT NULL,  --- Comma separated list of Tags associated with this\n  `CreatedAt` datetime DEFAULT NULL,      -- Created At Timestamp\n  `UpdatedAt` datetime NOT NULL,              -- Updated At Timestamp\n  `DeletedAt` datetime DEFAULT NULL,             -- Delete At Timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n\n```\n\n\n\n##\n\n\n14. otp\n``` sql\nCREATE TABLE `otp` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each otp\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,  --- id of user\n  `Purpose` varchar(64) DEFAULT NULL,                                 -- what is the purpose of this O\n  `Otp` varchar(8) DEFAULT NULL,                                     -- One Time Password\n  `ValidFrom` datetime NOT NULL,                                     -- Valid from and till when it\n  `ValidTill` datetime NOT NULL,                                     -- will be valid\n  `Utilized` tinyint(1) NOT NULL 

In [4]:
text_splitter=CharacterTextSplitter.from_tiktoken_encoder(separator="##",chunk_size=250,chunk_overlap=0)
docs=text_splitter.split_documents(data)

Created a chunk of size 380, which is longer than the specified 250
Created a chunk of size 522, which is longer than the specified 250
Created a chunk of size 581, which is longer than the specified 250
Created a chunk of size 432, which is longer than the specified 250
Created a chunk of size 562, which is longer than the specified 250
Created a chunk of size 641, which is longer than the specified 250
Created a chunk of size 430, which is longer than the specified 250
Created a chunk of size 709, which is longer than the specified 250
Created a chunk of size 890, which is longer than the specified 250
Created a chunk of size 715, which is longer than the specified 250
Created a chunk of size 747, which is longer than the specified 250
Created a chunk of size 498, which is longer than the specified 250
Created a chunk of size 576, which is longer than the specified 250
Created a chunk of size 895, which is longer than the specified 250
Created a chunk of size 863, which is longer than the specified 250
Created a chunk of size 496, which is longer than the specified 250
Created a chunk of size 1246, which is longer than the specified 250
Created a chunk of size 295, which is longer than the specified 250
Created a chunk of size 687, which is longer than the specified 250
Created a chunk of size 425, which is longer than the specified 250
Created a chunk of size 285, which is longer than the specified 250
Created a chunk of size 562, which is longer than the specified 250
Created a chunk of size 270, which is longer than the specified 250
Created a chunk of size 516, which is longer than the specified 250
Created a chunk of size 433, which is longer than the specified 250
Created a chunk of size 363, which is longer than the specified 250
Created a chunk of size 694, which is longer than the specified 250
Created a chunk of size 654, which is longer than the specified 250
Created a chunk of size 393, which is longer than the specified 250

In [6]:
len(docs)
docs[31].page_content

"32. organizations\n``` sql\nCREATE TABLE `organizations` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each organizations\n  `Name` varchar(64) DEFAULT '',\n  `Type` enum('Clinic','Hospital','Diagnostic Lab','Diagnostic Lab - Pathology','Diagnostic Lab - Imaging','Pharmacy','Ambulance Service','Government Primary Health Care Centre','Government Nodal Hospital','Government District Hospital','Municipal Hospital','Blood Bank','Nursing Home','Specialized Care Centre','Ambulatory Procedure Centre','Social Health','Unknown') NOT NULL DEFAULT 'Unknown', ---name of organization\n  `ContactUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --- contactid of user from organization's member\n  `ContactPhone` varchar(16) NOT NULL, ---contact number of organization's member\n  `ContactEmail` varchar(50) DEFAULT NULL, ---contact email of organization's member\n  `About` varchar(512) DEFAULT NULL, ---organizations detail\n  `ParentOrganizationId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---parentorganizationid of this orgnization\n  `OperationalSince` datetime DEFAULT NULL, ---date from organization is working\n  `ImageResourceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,\n  `IsHealthFacility` tinyint(1) NOT NULL DEFAULT '1', \n  `NationalHealthFacilityRegistryId` varchar(64) DEFAULT NULL, ---id of national facility registry\n  `CreatedAt` datetime DEFAULT NULL,           --creation date-time stamp\n  `UpdatedAt` datetime NOT NULL,                 --update date-time stamp\n  `DeletedAt` datetime DEFAULT NULL,               --delete date-time stamp if record is\n  PRIMARY KEY (`id`),\n  KEY `organizations__contact_phone` (`ContactPhone`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n\n```\n``` sql \n---users.PersonId can be joined with persons.id\n---user_tasks.UserId can be joined with users.id\n---user_login_sessions.UserId can be joined with users.id\n---user_device_details.UserId can be joined with users.id\n-- role_privileges.RoleId can be joined with roles.id\n-- person_roles.PersonId can be joined with persons.id\n-- person_addresses.PersonId can be joined with persons.id\n--  person_addresses.AddressId can be joined  with addresses.id\n-- patients.PersonId can be joined with persons.id\n--  patients.UserId can be joined with users.id\n-- patient_insurances.PatientUserId can be joined with patients.id\n-- patient_health_profiles.PatientUserId can be joined with users.id\n-- patient_goals.PatientUserId can be joined with users.id\n-- patient_emergency_contacts.PatientUserId can be joined with users.id\n-- patient_emergency_contacts.ContactPerson can be joined with persons\n-- patient_emergency_contacts.AddressId  can be joined with addresses.id\n-- patient_emergency_contacts.OrganizationId can be joined with organizations.id\n-- patient_documents.PatientUserId can be joined with users.id\n-- otp.UserId can be joined with users.id\n-- health_priorities.PatientUserId can be joined with users.id\n-- health_priorities.UserId can be joined with users.id\n-- doctors.PersonId  can be joined with persons.id\n-- custom_tasks.UserId can be joined with users.id\n-- blood_donors.UserId can be joined with users.id\n--  blood_donors.PersonId can  be joined with persons.id\n-- blood_donation_volunteers.UserId can be joined with users.id\n-- blood_donation_volunteers.PersonId  can be joined with persons.id\n--- biometrics_body_weight.PatientUserId can be joined with users.id\n--- biometrics_blood_cholesterol.PersonId can be joined with persons.id\n--- biometrics_blood_glucose.PersonId can be joined with persons.id\n--- biometrics_blood_oxygen_saturation.PatientUserId can be joined with users.id\n--- biometrics_blood_pressure.PersonId can be joined with persons.id\n--- biometrics_body_height.PersonId can be joined with persons.id\n---  biometrics_body_height.PatientUserId can be joined with users.id\n--- biometrics_body_temperature.PatientUserId can be joined with users.id\n```"

In [7]:
# db = Chroma.from_documents(docs, embedding_function)
# save to disk
db2 = Chroma.from_documents(docs, embedding_function, persist_directory="./try_few_show")
# docs = db2.similarity_search(query)

In [89]:
query=f"Can you provide the distinct priority_types for the patient with the ID 'desired_patient_id'?"
# docs = db.similarity_search(query)
# load from disk
db3 = Chroma(persist_directory="./try_few_show", embedding_function=embedding_function)
docs = db3.similarity_search(query)
print(docs[0].page_content)

12. health_priorities
``` sql
CREATE TABLE `health_priorities` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each health_priorities
  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --- id of patient
  `Source` varchar(32) NOT NULL, ---source of the priority
  `Provider` varchar(64) NOT NULL, ---provider who set this priority
  `ProviderEnrollmentId` varchar(32) NOT NULL, ---enrollment number in provider system
  `ProviderCareplanCode` varchar(64) NOT NULL,  ---code that identifies care plan in provider system
  `ProviderCareplanName` varchar(64) NOT NULL, ---name of care plan in provider system
  `HealthPriorityType` varchar(64) DEFAULT NULL, ---type of health priority: chronic disease,
  `StartedAt` datetime DEFAULT NULL,  ---when user started to have this health priority
  `CompletedAt` datetime DEFAULT NULL, --- when user completed treatment for this health priority
  `Status` varchar(128) DEFAULT NULL, ---status of health priority: active,completed
  `ScheduledEndDate` datetime DEFAULT NULL, ---date when treatment should be finished
  `IsPrimary` tinyint(1) DEFAULT NULL, ---is primary health priority or not
  `CreatedAt` datetime DEFAULT NULL,          ----created at timestamp
  `UpdatedAt` datetime NOT NULL,                -----updated at timestamp
  `DeletedAt` datetime DEFAULT NULL,                 -------delete at timestamp
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

In [55]:
docs

[Document(page_content="16. patientemergencycontacts\n``` sql\nCREATE TABLE `patient_emergency_contacts` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patient_emergency_contacts\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, --id of patient\n  `ContactPersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,  --id of contact person\n  `ContactRelation` varchar(64) NOT NULL DEFAULT 'Doctor',                       --relation to the patient\n  `AddressId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,    --address id\n  `OrganizationId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --organization id\n  `IsAvailableForEmergency` tinyint(1) NOT NULL DEFAULT '0',                       --is available for emergencies?\n  `TimeOfAvailability` varchar(256) DEFAULT NULL,                                --time available to be called or visited\n  `Description` varchar(256) DEFAULT NULL,                                       --description about emergency contact\n  `AdditionalPhoneNumbers` varchar(64) DEFAULT NULL, --contact number\n  `CreatedAt` datetime DEFAULT NULL,                  --created at timestamp\n  `UpdatedAt` datetime NOT NULL,                        --updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,  \n  PRIMARY KEY (`id`),\n  KEY `PatientUserId` (`PatientUserId`),\n  KEY `ContactPersonId` (`ContactPersonId`),\n  KEY `AddressId` (`AddressId`),\n  KEY `OrganizationId` (`OrganizationId`),\n  CONSTRAINT `patient_emergency_contacts_ibfk_41` FOREIGN KEY (`PatientUserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `patient_emergency_contacts_ibfk_42` FOREIGN KEY (`ContactPersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `patient_emergency_contacts_ibfk_43` FOREIGN KEY (`AddressId`) REFERENCES `addresses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `patient_emergency_contacts_ibfk_44` FOREIGN KEY (`OrganizationId`) REFERENCES `organizations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```", metadata={'source': './try.md'}),
 Document(page_content="20. patientsinfo\n``` sql\nCREATE TABLE `patients` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patients\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of user\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of person\n  `DisplayId` varchar(24) NOT NULL, ---display id of patient\n  `NationalHealthId` varchar(32) DEFAULT NULL, --- national health id of patient\n  `MedicalProfileId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --- medical profile id\n  `TerraUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,  --- Terra User Id\n  `TerraProvider` varchar(32) DEFAULT NULL,  --- Terra Provider Name\n  `TerraScopes` varchar(256) DEFAULT NULL,   --- Terra Scopes\n  `EhrId` varchar(256) DEFAULT NULL,           --- Electronic Health Record Id\n  `HealthSystem` varchar(256) DEFAULT NULL,     --- Health System Name\n  `AssociatedHospital` varchar(256) DEFAULT NULL, --hospital associated\n  `DonorAcceptance` enum('Send','NotSend','Accepted') NOT NULL DEFAULT 'NotSend', -- donor acceptance status\n  `IsRemindersLoaded` tinyint(1) NOT NULL DEFAULT '0', -- is reminder loaded or not\n  `CreatedAt` datetime DEFAULT NULL,              --- created at timestamp\n  `UpdatedAt` datetime NOT NULL,                   --- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                 --- deleted at timestamp\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `patients_ibfk_21` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `patients_ibfk_22` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```", metadata={'source': './try.md'}),
 Document(page_content="18. patienthealthprofiles\n``` sql\nCREATE TABLE `patient_health_profiles` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patient_health_profiles\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,  ---id of patient\n  `BloodGroup` varchar(16) DEFAULT '',--blood group\n  `BloodTransfusionDate` datetime DEFAULT NULL,  --last blood transfusion date\n  `BloodDonationCycle` int DEFAULT NULL,         --how many times donated in a life\n  `MajorAilment` varchar(128) DEFAULT '',         --major health issue\n  `OtherConditions` varchar(512) DEFAULT '',       --other health issues\n  `IsDiabetic` tinyint(1) DEFAULT NULL, --diabetic or not\n  `HasHeartAilment` tinyint(1) DEFAULT NULL,--heart ailment\n  `MaritalStatus` varchar(128) DEFAULT NULL,       --marrital status\n  `Ethnicity` varchar(128) DEFAULT NULL,            --ethinicity\n  `Race` varchar(128) DEFAULT '', \n  `StrokeSurvivorOrCaregiver` varchar(128) DEFAULT NULL,    --stroke survivor or care giver\n  `LivingAlone` tinyint(1) DEFAULT NULL,              --living alone or with family/spouse\n  `WorkedPriorToStroke` tinyint(1) DEFAULT NULL,      --worked before stroke\n  `Nationality` varchar(64) DEFAULT NULL,              --nationality\n  `Occupation` varchar(64) DEFAULT NULL,                 --occupation\n  `SedentaryLifestyle` tinyint(1) NOT NULL DEFAULT '0', ---sedantary lifestyle or active lifestyle\n  `IsSmoker` tinyint(1) NOT NULL DEFAULT '0',             --smoking or not\n  `SmokingSeverity` enum('Low','Medium','High','Critical','Unknown') NOT NULL DEFAULT 'Low', --smoking severity level\n  `SmokingSince` datetime DEFAULT NULL,                 --start smoking from\n  `IsDrinker` tinyint(1) NOT NULL DEFAULT '0',            --drinking alcohol or not\n  `DrinkingSeverity` enum('Low','Medium','High','Critical','Unknown') NOT NULL DEFAULT 'Low', --alcohol drinking severity\n  `DrinkingSince` datetime DEFAULT NULL,                 --start drinking from\n  `SubstanceAbuse` tinyint(1) NOT NULL DEFAULT '0',      --substance abuse or not\n  `ProcedureHistory` varchar(512) DEFAULT NULL,           --history of procedures done\n  `ObstetricHistory` varchar(512) DEFAULT NULL,           --obstrtric history\n  `OtherInformation` varchar(512) DEFAULT NULL,             --any other important information about the user\n  `TobaccoQuestion` text,                                      --tobacco questionnaire data\n  `TobaccoQuestionAns` tinyint(1) DEFAULT NULL,                --answers to the questions\n  `TypeOfStroke` varchar(128) DEFAULT NULL,                      --type of stroke\n  `HasHighBloodPressure` tinyint(1) DEFAULT NULL, --blood pressure detail\n  `HasHighCholesterol` tinyint(1) DEFAULT NULL, --cholesterol detail\n  `HasAtrialFibrillation` tinyint(1) DEFAULT NULL,      --atrial fibrillation detail\n  `CreatedAt` datetime DEFAULT NULL, ---created at timestamp     \n  `UpdatedAt` datetime NOT NULL,     ---updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,     --deleted at timestamp\n  PRIMARY KEY (`id`),\n  KEY `PatientUserId` (`PatientUserId`),\n  CONSTRAINT `patient_health_profiles_ibfk_1` FOREIGN KEY (`PatientUserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE\n)\n\n```", metadata={'source': './try.md'}),
 Document(page_content="15. patientdocuments\n``` sql\nCREATE TABLE `patient_documents` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each documents\n  `EhrId` varchar(128) DEFAULT NULL,  ---electronic  health record id\n  `DisplayId` varchar(32) NOT NULL,    --displayed document Id to the user\n  `DocumentType` varchar(128) NOT NULL DEFAULT 'Unknown', ---type of document\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---user who uploaded this document\n  `MedicalPractitionerUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who uploaded this document\n  `MedicalPractionerRole` varchar(64) DEFAULT NULL,    ---doctor's role in this document\n  `UploadedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who uploaded the document\n  `AssociatedVisitId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---visit related to this document\n  `AssociatedVisitType` varchar(64) DEFAULT 'Unknown', ---visit type associated with this document\n  `AssociatedOrderId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---order id if any\n  `AssociatedOrderType` varchar(64) DEFAULT NULL,        ---order type if any\n  `FileName` varchar(512) DEFAULT NULL,                   ---file name as per client system\n  `ResourceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---unique resource id from cloud storage provider\n  `AuthenticatedUrl` varchar(512) NOT NULL DEFAULT '',       ---authenticated url to access the file\n  `MimeType` varchar(64) DEFAULT NULL,                 ----mimetype of the file\n  `SizeInKBytes` float DEFAULT NULL,                       ---size of the file in KB\n  `RecordDate` datetime DEFAULT NULL,                       ---date when the document was added/\n  `UploadedDate` datetime DEFAULT NULL,                       ---date when the document was uploaded by\n  `CreatedAt` datetime DEFAULT NULL,                            ---created at timestamp\n  `UpdatedAt` datetime NOT NULL,                                  ---updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                                  ---delete at timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```", metadata={'source': './try.md'})]

In [18]:
len(docs)
# docs[8]

4

In [7]:
db = Chroma.from_documents(docs, embeddings, persist_directory="./try_few_show")
db.persist()

# Retriever for searching the document store

In [8]:
db_new_connection=Chroma(persist_directory='./try_few_show',embedding_function=embeddings)

In [17]:
retriever=db_new_connection.as_retriever()
result=retriever.get_relevant_documents("9i")

In [18]:
result[0].page_content

"6f.\n``` sql\nCREATE TABLE `patients` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patients\n  `UserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of user\n  `PersonId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of person\n  `DisplayId` varchar(24) NOT NULL, ---display id of patient\n  `NationalHealthId` varchar(32) DEFAULT NULL, --- national health id of patient\n  `MedicalProfileId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, --- medical profile id\n  `TerraUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,  --- Terra User Id\n  `TerraProvider` varchar(32) DEFAULT NULL,  --- Terra Provider Name\n  `TerraScopes` varchar(256) DEFAULT NULL,   --- Terra Scopes\n  `EhrId` varchar(256) DEFAULT NULL,           --- Electronic Health Record Id\n  `HealthSystem` varchar(256) DEFAULT NULL,     --- Health System Name\n  `AssociatedHospital` varchar(256) DEFAULT NULL, --hospital associated\n  `DonorAcceptance` enum('Send','NotSend','Accepted') NOT NULL DEFAULT 'NotSend', -- donor acceptance status\n  `IsRemindersLoaded` tinyint(1) NOT NULL DEFAULT '0', -- is reminder loaded or not\n  `CreatedAt` datetime DEFAULT NULL,              --- created at timestamp\n  `UpdatedAt` datetime NOT NULL,                   --- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                 --- deleted at timestamp\n  PRIMARY KEY (`id`),\n  KEY `UserId` (`UserId`),\n  KEY `PersonId` (`PersonId`),\n  CONSTRAINT `patients_ibfk_21` FOREIGN KEY (`UserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE,\n  CONSTRAINT `patients_ibfk_22` FOREIGN KEY (`PersonId`) REFERENCES `persons` (`id`) ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```"

In [14]:
docs=db_new_connection.similarity_search("Pdetails")

In [15]:
len(docs)

4

In [16]:
docs

[Document(page_content="17. patientgoals\n``` sql\nCREATE TABLE `patient_goals` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,-- patient id \n  `ProviderEnrollmentId` varchar(64) DEFAULT NULL, -- provider enrollement Id if any\n  `Provider` varchar(255) DEFAULT NULL,  -- Provider name\n  `ProviderCareplanName` varchar(32) DEFAULT NULL, -- care plan name\n  `ProviderCareplanCode` varchar(32) DEFAULT NULL, --care plan code\n  `ProviderGoalCode` varchar(64) DEFAULT NULL, -- Goal Code\n  `Title` varchar(64) NOT NULL,--goal title\n  `Sequence` varchar(64) DEFAULT NULL, --sequence in which goal is set by the user\n  `HealthPriorityId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, -- id of health priority\n  `GoalAchieved` tinyint(1) DEFAULT '0',--goal achived\n  `GoalAbandoned` tinyint(1) DEFAULT '0',--goal abondoned\n  `StartedAt` datetime DEFAULT NULL,--goal started time\n  `CompletedAt` datetime DEFAULT NULL,--goal complete time\n  `ScheduledEndDate` datetime DEFAULT NULL,-- goal end date\n  `CreatedAt` datetime DEFAULT NULL,   -- created at timestamp\n  `UpdatedAt` datetime NOT NULL,        -- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,       -- deleted at timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n\n```", metadata={'source': './try.md'}),
 Document(page_content="18. patienthealthprofiles\n``` sql\nCREATE TABLE `patient_health_profiles` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patient_health_profiles\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,  ---id of patient\n  `BloodGroup` varchar(16) DEFAULT '',--blood group\n  `BloodTransfusionDate` datetime DEFAULT NULL,  --last blood transfusion date\n  `BloodDonationCycle` int DEFAULT NULL,         --how many times donated in a life\n  `MajorAilment` varchar(128) DEFAULT '',         --major health issue\n  `OtherConditions` varchar(512) DEFAULT '',       --other health issues\n  `IsDiabetic` tinyint(1) DEFAULT NULL, --diabetic or not\n  `HasHeartAilment` tinyint(1) DEFAULT NULL,--heart ailment\n  `MaritalStatus` varchar(128) DEFAULT NULL,       --marrital status\n  `Ethnicity` varchar(128) DEFAULT NULL,            --ethinicity\n  `Race` varchar(128) DEFAULT '', \n  `StrokeSurvivorOrCaregiver` varchar(128) DEFAULT NULL,    --stroke survivor or care giver\n  `LivingAlone` tinyint(1) DEFAULT NULL,              --living alone or with family/spouse\n  `WorkedPriorToStroke` tinyint(1) DEFAULT NULL,      --worked before stroke\n  `Nationality` varchar(64) DEFAULT NULL,              --nationality\n  `Occupation` varchar(64) DEFAULT NULL,                 --occupation\n  `SedentaryLifestyle` tinyint(1) NOT NULL DEFAULT '0', ---sedantary lifestyle or active lifestyle\n  `IsSmoker` tinyint(1) NOT NULL DEFAULT '0',             --smoking or not\n  `SmokingSeverity` enum('Low','Medium','High','Critical','Unknown') NOT NULL DEFAULT 'Low', --smoking severity level\n  `SmokingSince` datetime DEFAULT NULL,                 --start smoking from\n  `IsDrinker` tinyint(1) NOT NULL DEFAULT '0',            --drinking alcohol or not\n  `DrinkingSeverity` enum('Low','Medium','High','Critical','Unknown') NOT NULL DEFAULT 'Low', --alcohol drinking severity\n  `DrinkingSince` datetime DEFAULT NULL,                 --start drinking from\n  `SubstanceAbuse` tinyint(1) NOT NULL DEFAULT '0',      --substance abuse or not\n  `ProcedureHistory` varchar(512) DEFAULT NULL,           --history of procedures done\n  `ObstetricHistory` varchar(512) DEFAULT NULL,           --obstrtric history\n  `OtherInformation` varchar(512) DEFAULT NULL,             --any other important information about the user\n  `TobaccoQuestion` text,                                      --tobacco questionnaire data\n  `TobaccoQuestionAns` tinyint(1) DEFAULT NULL,                --answers to the questions\n  `TypeOfStroke` varchar(128) DEFAULT NULL,                      --type of stroke\n  `HasHighBloodPressure` tinyint(1) DEFAULT NULL, --blood pressure detail\n  `HasHighCholesterol` tinyint(1) DEFAULT NULL, --cholesterol detail\n  `HasAtrialFibrillation` tinyint(1) DEFAULT NULL,      --atrial fibrillation detail\n  `CreatedAt` datetime DEFAULT NULL, ---created at timestamp     \n  `UpdatedAt` datetime NOT NULL,     ---updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,     --deleted at timestamp\n  PRIMARY KEY (`id`),\n  KEY `PatientUserId` (`PatientUserId`),\n  CONSTRAINT `patient_health_profiles_ibfk_1` FOREIGN KEY (`PatientUserId`) REFERENCES `users` (`id`) ON UPDATE CASCADE\n)\n\n```", metadata={'source': './try.md'}),
 Document(page_content="15. patientdocuments\n``` sql\nCREATE TABLE `patient_documents` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each documents\n  `EhrId` varchar(128) DEFAULT NULL,  ---electronic  health record id\n  `DisplayId` varchar(32) NOT NULL,    --displayed document Id to the user\n  `DocumentType` varchar(128) NOT NULL DEFAULT 'Unknown', ---type of document\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---user who uploaded this document\n  `MedicalPractitionerUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who uploaded this document\n  `MedicalPractionerRole` varchar(64) DEFAULT NULL,    ---doctor's role in this document\n  `UploadedByUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---user who uploaded the document\n  `AssociatedVisitId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---visit related to this document\n  `AssociatedVisitType` varchar(64) DEFAULT 'Unknown', ---visit type associated with this document\n  `AssociatedOrderId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, ---order id if any\n  `AssociatedOrderType` varchar(64) DEFAULT NULL,        ---order type if any\n  `FileName` varchar(512) DEFAULT NULL,                   ---file name as per client system\n  `ResourceId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---unique resource id from cloud storage provider\n  `AuthenticatedUrl` varchar(512) NOT NULL DEFAULT '',       ---authenticated url to access the file\n  `MimeType` varchar(64) DEFAULT NULL,                 ----mimetype of the file\n  `SizeInKBytes` float DEFAULT NULL,                       ---size of the file in KB\n  `RecordDate` datetime DEFAULT NULL,                       ---date when the document was added/\n  `UploadedDate` datetime DEFAULT NULL,                       ---date when the document was uploaded by\n  `CreatedAt` datetime DEFAULT NULL,                            ---created at timestamp\n  `UpdatedAt` datetime NOT NULL,                                  ---updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,                                  ---delete at timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n```", metadata={'source': './try.md'}),
 Document(page_content='19. patientinsurances\n``` sql\nCREATE TABLE `patient_insurances` (\n  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---Unique ID for each patient_insurances\n  `PatientUserId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, ---id of patient\n  `InsuranceProvider` varchar(64) DEFAULT NULL, --insurance provider name\n  `InsurancePolicyCode` varchar(64) DEFAULT NULL, ---policy code\n  `ValidFrom` datetime DEFAULT NULL,-- insurance valid from\n  `ValidTill` datetime DEFAULT NULL,-- insurance valid till\n  `CreatedAt` datetime DEFAULT NULL,  --- created at timestamp\n  `UpdatedAt` datetime NOT NULL,         --- updated at timestamp\n  `DeletedAt` datetime DEFAULT NULL,         --- deleted at timestamp\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n\n```', metadata={'source': './try.md'})]

In [ ]:
from openai import OpenAI

client = OpenAI(
    base_url = 'http://localhost:11434/v1',
    api_key='ollama', # required, but unused
)
query="give the body temperature for this particular user id."
response = client.chat.completions.create(
  model="phi",
  messages=[
    {"role": "system", "content": "You are a SQL developer, user ask you text question aand your work is to provide just MYSQL query to text question."},
    # {"role": "user", "content": "Who won the world series in 2020?"},
    # {"role": "assistant", "content": f"The LA Dodgers won in 2020.{model}"},
    {"role": "user", "content": f"{query}"}
  ]
)
# print(response.choices[0].message.content)

In [ ]:
print(response.choices[0].message.content)